name: deploy-workflow
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          token: ${{ secrets.GH_TOKEN }}
      - run: yarn
      - run: yarn build
      - name: Commit new build
      - run: |
          mv out/* .
          git add index.html 404.html _next 
          git commit -m "build v0.0.1"
          git push -f origin github-pages